use_frameworks!

platform :ios, '8.0'

target 'SevenSegmentIndicator_Example' do
  pod 'SevenSegmentIndicator', :path => '../'

  target 'SevenSegmentIndicator_Tests' do
    inherit! :search_paths

    
  end
end
